name: app_qrcode_scanner
description: QRCode Scanner with camera scanner and photo scanner function. Available in both Android and iOS Device. Forked from qr_code_scanner
version: 0.0.2
homepage: https://www.goldhub.hk

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.2
  qr_code_tools: ^0.0.6

dev_dependencies: 
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: net.touchcapture.qr.flutterqr
        pluginClass: FlutterQrPlugin
      ios:
        pluginClass: FlutterQrPlugin
